name: Build Server Image

on:
  push:
    branches:
      - 'main'
    paths:
      - 'server/**'
      - '.github/workflows/build-server.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make image
      - name: 'Push to ghcr.io'
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login $IMAGE_REG -u $GITHUB_ACTOR --password-stdin
          make push
